#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_GIT_CONFIG ]; then
     touch $SERVICE_GIT_CONFIG
  fi

  config::load_file $SERVICE_GIT_CONFIG

  if [ -z "$SERVICE_GIT_DOMAIN" ]; then
    inquirer::text "请输入 SERVICE_GIT_DOMAIN:" value
    config::set SERVICE_GIT_DOMAIN $value $SERVICE_GIT_CONFIG
  fi

  if [ -z "$SERVICE_GIT_DRONE_DOMAIN" ]; then
    inquirer::text "请输入 SERVICE_GIT_DRONE_DOMAIN:" value
    config::set SERVICE_GIT_DRONE_DOMAIN $value $SERVICE_GIT_CONFIG
  fi

  if [ -z "$SERVICE_GIT_DRONE_RPC_SECRET" ]; then
    inquirer::text "请输入 SERVICE_GIT_DRONE_RPC_SECRET:" value "$(os::uuid)"
    config::set SERVICE_GIT_DRONE_RPC_SECRET $value $SERVICE_GIT_CONFIG
  fi

  if [ -z "$SERVICE_GIT_DRONE_ADMIN_USER" ]; then
    inquirer::text "请输入 SERVICE_GIT_DRONE_ADMIN_USER:" value
    config::set SERVICE_GIT_DRONE_ADMIN_USER $value $SERVICE_GIT_CONFIG
  fi

  # if [ -z "$SECRET_KEY" ]; then
  #   inquirer::text "请输入 SECRET_KEY:" value "$(os::uuid)"
  #   config::set SECRET_KEY $value $SERVICE_GIT_CONFIG
  # fi
  
  # load again
  config::load_file $SERVICE_GIT_CONFIG
  # @TODO
  export SERVICE_GIT_DOMAIN=$SERVICE_GIT_DOMAIN
  export SERVICE_GIT_DRONE_DOMAIN=$SERVICE_GIT_DRONE_DOMAIN
  export SERVICE_GIT_DRONE_RPC_SECRET=$SERVICE_GIT_DRONE_RPC_SECRET
  export SERVICE_GIT_DRONE_ADMIN_USER=$SERVICE_GIT_DRONE_ADMIN_USER
  # export SECRET_KEY=$SECRET_KEY
}

check $@
